// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SebUzduotisApi.Context;

namespace SebUzduotisApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SebUzduotisApi.Models.Agreement", b =>
                {
                    b.Property<int>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseRateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Margin")
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementId");

                    b.HasIndex("BaseRateId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("SebUzduotisApi.Models.BaseRate", b =>
                {
                    b.Property<int>("BaseRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseRateCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BaseRateId");

                    b.ToTable("BaseRates");
                });

            modelBuilder.Entity("SebUzduotisApi.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.HasIndex("PersonalId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SebUzduotisApi.Models.Agreement", b =>
                {
                    b.HasOne("SebUzduotisApi.Models.BaseRate", "BaseRate")
                        .WithMany("Agreements")
                        .HasForeignKey("BaseRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SebUzduotisApi.Models.Customer", "Customer")
                        .WithMany("Agreements")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseRate");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SebUzduotisApi.Models.BaseRate", b =>
                {
                    b.Navigation("Agreements");
                });

            modelBuilder.Entity("SebUzduotisApi.Models.Customer", b =>
                {
                    b.Navigation("Agreements");
                });
#pragma warning restore 612, 618
        }
    }
}
